import type { ProductDTO } from '@tamas/shared';
import type { ProductForm } from './types';

export const ATTR_TYPE_LABELS: Record<string, string> = {
  text: 'متن ساده',
  number: 'عدد',
  boolean: 'بله / خیر',
  select: 'چند گزینه‌ای',
};

export const MULTI_SEP = '، ';

export const blank = (): ProductForm => ({
  productId: '',
  sku: '',
  title: '',
  model: '',
  categoryName: '',
  brandName: '',
  color: '',
  colorEn: '',
  colorCode: '',
  price: 0,
  oldPrice: null,
  discount: 0,
  stock: 0,
  kermanStock: 0,
  tehranStock: 0,
  otherStocks: {},
  parentProductId: '',
  warranty: '',
  sellType: '',
  seller: '',
  promotion: false,
  status: 'active',
  imageUrl: '',
  gallery: [],
  attributes: [],
  sortOrder: 0,
  subTitle: '',
  description: '',
  keywords: '',
  slug: '',
  ribbon: '',
  type: 'physical',
  weight: 0,
  dimensions: '',
  tracking: true,
  digikalaLink: '',
  targetSiteUrl: '',
  trackingLinks: [],
  bundleItems: [],
});

export const fromProduct = (p: ProductDTO): ProductForm => ({
  productId: p.productId,
  sku: p.sku ?? '',
  title: p.title,
  model: p.model ?? '',
  categoryName: p.categoryName ?? '',
  brandName: p.brandName ?? '',
  color: p.color ?? '',
  colorEn: p.colorEn ?? '',
  colorCode: p.colorCode ?? '',
  price: p.price,
  oldPrice: p.oldPrice,
  discount: p.discount,
  stock: p.stock,
  kermanStock: p.kermanStock,
  tehranStock: p.tehranStock,
  otherStocks: p.otherStocks ?? {},
  parentProductId: p.parentProductId ?? '',
  warranty: p.warranty ?? '',
  sellType: p.sellType ?? '',
  seller: p.seller ?? '',
  promotion: p.promotion,
  status: p.status,
  imageUrl: p.imageUrl ?? '',
  gallery: p.gallery,
  attributes: p.attributes,
  sortOrder: p.sortOrder,
  subTitle: p.subTitle ?? '',
  description: p.description ?? '',
  keywords: p.keywords ?? '',
  slug: p.slug ?? '',
  ribbon: p.ribbon ?? '',
  type: p.type ?? 'physical',
  weight: p.weight ?? 0,
  dimensions: p.dimensions ?? '',
  tracking: p.tracking ?? true,
  digikalaLink: p.digikalaLink ?? '',
  targetSiteUrl: p.targetSiteUrl ?? '',
  trackingLinks: (p.trackingLinks ?? []).map((link) => ({ siteId: link.siteId, url: link.url })),
  bundleItems: p.bundleItems ?? [],
});
