import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '../../lib/api';
import { useToast } from '../../components/Toast';

interface WalletUser { userId:number; name:string; lastName:string; phone:string; storeName:string; balance:number; lifetimeCredit:number; lifetimeDebit:number; isFrozen:boolean }
interface WalletList { items:WalletUser[]; total:number; stats:{ totalBalance:number; totalCredit:number; totalDebit:number; frozen:number } }
interface Entry { id:number; direction:'credit'|'debit'; amount:number; description:string; balanceAfter:number; createdAt:string }
const money = (n:number) => n.toLocaleString('fa-IR');

export function WalletsPage() {
  const toast = useToast(); const client = useQueryClient();
  const [search,setSearch]=useState(''); const [selected,setSelected]=useState<WalletUser|null>(null); const [direction,setDirection]=useState<'credit'|'debit'>('credit'); const [amount,setAmount]=useState(''); const [description,setDescription]=useState('');
  const list=useQuery({queryKey:['admin','wallets',search],queryFn:()=>api.get<WalletList>('/admin/wallets',{q:search,perPage:100})});
  const history=useQuery({queryKey:['admin','wallet-history',selected?.userId],queryFn:()=>api.get<{items:Entry[]}>(`/admin/wallets/${selected!.userId}/transactions`),enabled:Boolean(selected)});
  const refresh=()=>client.invalidateQueries({queryKey:['admin','wallets']});
  const adjust=useMutation({mutationFn:()=>api.post(`/admin/wallets/${selected!.userId}/adjust`,{direction,amount:Number(amount),description}),onSuccess:async()=>{toast.ok('تراکنش کیف پول ثبت شد.');setAmount('');setDescription('');await refresh();await history.refetch()},onError:e=>toast.error((e as Error).message)});
  const freeze=useMutation({mutationFn:(isFrozen:boolean)=>api.patch(`/admin/wallets/${selected!.userId}/status`,{isFrozen}),onSuccess:async()=>{toast.ok('وضعیت کیف پول به‌روزرسانی شد.');await refresh();setSelected(s=>s?{...s,isFrozen:!s.isFrozen}:s)},onError:e=>toast.error((e as Error).message)});
  const stats=list.data?.stats;
  return <div className="a-page a-fade"><section className="a-page-head"><div className="a-titles"><h2 className="a-title">مدیریت کیف پول‌ها</h2><p className="a-subtitle">کنترل موجودی، ثبت اصلاحات مالی، مسدودسازی و مشاهده دفترکل کاربران</p></div></section>
    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 mb-5">{[['موجودی کل',stats?.totalBalance],['کل واریزها',stats?.totalCredit],['کل برداشت‌ها',stats?.totalDebit],['مسدود',stats?.frozen]].map(([label,value])=><article className="a-card p-5" key={String(label)}><p className="text-xs glass-text-t3">{label}</p><strong className="block mt-2 text-xl text-emerald-400">{money(Number(value||0))}{label==='مسدود'?'':' تومان'}</strong></article>)}</section>
    <section className="a-card a-card--flush"><div className="p-4 border-b glass-border"><input className="a-input w-full max-w-md" placeholder="جستجو نام، فروشگاه یا موبایل…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="a-table-wrap"><table className="a-table"><thead><tr><th>کاربر</th><th>موبایل</th><th>موجودی</th><th>واریز / برداشت</th><th>وضعیت</th><th></th></tr></thead><tbody>{list.isLoading?<tr><td colSpan={6} className="a-empty">در حال دریافت…</td></tr>:list.data?.items.map(item=><tr key={item.userId}><td><b>{`${item.name} ${item.lastName}`.trim()||'بدون نام'}</b><small className="block glass-text-t3">{item.storeName||'—'}</small></td><td dir="ltr">{item.phone}</td><td className="font-bold text-emerald-400">{money(item.balance)}</td><td>{money(item.lifetimeCredit)} / {money(item.lifetimeDebit)}</td><td><span className={`chip ${item.isFrozen?'chip-rose':'chip-brand'}`}>{item.isFrozen?'مسدود':'فعال'}</span></td><td><button className="a-btn a-btn--ghost" onClick={()=>setSelected(item)}>مدیریت</button></td></tr>)}</tbody></table></div></section>
    {selected&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 backdrop-blur-md p-4" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><section className="a-card w-full max-w-2xl max-h-[90vh] overflow-auto p-6"><div className="flex justify-between gap-4"><div><h3 className="a-title text-lg">{`${selected.name} ${selected.lastName}`}</h3><p className="a-subtitle">موجودی: {money(selected.balance)} تومان</p></div><button className="a-btn a-btn--ghost" onClick={()=>setSelected(null)}>✕</button></div><div className="grid sm:grid-cols-2 gap-3 mt-5"><select className="a-input" value={direction} onChange={e=>setDirection(e.target.value as any)}><option value="credit">افزایش موجودی</option><option value="debit">کاهش موجودی</option></select><input className="a-input" type="number" placeholder="مبلغ (تومان)" value={amount} onChange={e=>setAmount(e.target.value)}/><textarea className="a-input sm:col-span-2" placeholder="علت اصلاح (اجباری)" value={description} onChange={e=>setDescription(e.target.value)}/><button className="a-btn a-btn--primary" disabled={adjust.isPending||!amount||description.trim().length<3} onClick={()=>adjust.mutate()}>ثبت تراکنش</button><button className={`a-btn ${selected.isFrozen?'a-btn--ghost':'a-btn--danger'}`} disabled={freeze.isPending} onClick={()=>freeze.mutate(!selected.isFrozen)}>{selected.isFrozen?'رفع مسدودی':'مسدود کردن کیف پول'}</button></div><h4 className="mt-7 mb-3 font-bold">آخرین تراکنش‌ها</h4><div>{history.data?.items.length===0?<p className="a-empty">تراکنشی ثبت نشده است.</p>:history.data?.items.map(x=><div key={x.id} className="flex justify-between gap-3 py-3 border-b glass-border"><div><b>{x.description}</b><small className="block glass-text-t3">{new Date(x.createdAt).toLocaleString('fa-IR')}</small></div><strong className={x.direction==='credit'?'text-emerald-400':'text-rose-400'}>{x.direction==='credit'?'+':'−'} {money(x.amount)}</strong></div>)}</div></section></div>}
  </div>;
}
