const SPREADSHEET_ID='1VjRRhxuLrr1HiEjLBNRrxXrZmk_pPjfu-s6xZY6bha4';
const SHEETS={products:'Products',categories:'Categories',brands:'Brands',colors:'Colors',users:'Users',orders:'Orders',settings:'Settings'};
function doGet(e){const p=e&&e.parameter?e.parameter:{},a=p.action||'catalog';let d;try{if(a==='catalog')d=getCatalog_();else if(a==='settings')d=getSettings_();else if(a==='products')d={ok:true,products:read_(SHEETS.products)};else if(a==='categories')d={ok:true,categories:read_(SHEETS.categories)};else if(a==='brands')d={ok:true,brands:read_(SHEETS.brands)};else if(a==='colors')d={ok:true,colors:read_(SHEETS.colors)};else d={ok:false,error:'Unknown action'}}catch(x){d={ok:false,error:String(x)}}return output_(d,p.callback)}
function doPost(e){try{const p=JSON.parse(e&&e.postData?e.postData.contents:'{}');if(p.action==='registerUser')return json_(registerUser_(p));if(p.action==='createOrder')return json_(createOrder_(p));return json_({ok:false,error:'Unknown action'})}catch(x){return json_({ok:false,error:String(x)})}}
function getCatalog_(){return{ok:true,products:read_(SHEETS.products),categories:read_(SHEETS.categories),brands:read_(SHEETS.brands),colors:read_(SHEETS.colors),settings:getSettings_().settings}}
function getSettings_(){const v=getSheet_(SHEETS.settings).getDataRange().getValues(),s={};v.slice(1).forEach(r=>{if(r[0]!=='')s[String(r[0])]=r[1]});return{ok:true,settings:s}}
function registerUser_(p){const sh=getSheet_(SHEETS.users),h=headers_(sh),need=['name','last_name','Store_name','phone_number','mobile_number','address','postal_code','certificate_file_url','actived'];need.forEach(x=>{if(h.indexOf(x)<0)throw Error('Users header not found: '+x)});const m=String(p.mobile_number||'').trim();if(!p.name||!p.last_name||!m)throw Error('name, last_name and mobile_number are required');const mi=h.indexOf('mobile_number');if(sh.getDataRange().getValues().slice(1).some(r=>String(r[mi]||'').trim()===m))return{ok:false,error:'این شماره موبایل قبلاً ثبت شده است.'};sh.appendRow(h.map(x=>x==='actived'?false:String(p[x]||'').trim()));return{ok:true,message:'User registered',user:{name:p.name,last_name:p.last_name,mobile_number:m,actived:false}}}
function createOrder_(p){const sh=getSheet_(SHEETS.orders),id='KP-'+Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'yyyyMMdd-HHmmss')+'-'+Math.floor(Math.random()*1000);sh.appendRow([id,new Date(),p.customer_name||'',p.phone||'',p.address||'',JSON.stringify(p.items||[]),Number(p.total||0),'new']);return{ok:true,order_id:id}}
function getSheet_(n){const s=SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName(n);if(!s)throw Error('Sheet not found: '+n);return s}
function headers_(s){return s.getRange(1,1,1,s.getLastColumn()).getValues()[0].map(x=>String(x).trim())}
function read_(n){const v=getSheet_(n).getDataRange().getValues();if(v.length<2)return[];const h=v[0].map(x=>String(x).trim());return v.slice(1).filter(r=>r.some(x=>x!==''&&x!==null)).map(r=>{const o={};h.forEach((k,i)=>{let x=r[i];if(k==='promotion'||k==='actived')x=x===true||String(x).toUpperCase()==='TRUE';o[k]=typeof x==='string'?x.trim():x});return o})}
function output_(o,c){if(c)return ContentService.createTextOutput(String(c).replace(/[^\w.$]/g,'')+'('+JSON.stringify(o)+');').setMimeType(ContentService.MimeType.JAVASCRIPT);return json_(o)}
function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
